name: example
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.5.0-152.0.dev

dependencies:
  ejson_annotation: ^0.3.0

dev_dependencies:
  custom_lint: ^0.6.2
  ejson_lint: ^0.3.0
  lints: ^3.0.0


