name: realm_macros
description: An experimental replacement for realm_generator using the macros package
version: 0.1.0

environment:
  sdk: ^3.5.0-152.0.dev # this will currently require dart from master

dependencies:
  macros: ^0.1.0-main.5
  collection: any
  realm_dart: ^2.2.1

dev_dependencies:
  _fe_analyzer_shared: any
  lints: ^3.0.0
  test: ^1.24.0