#!/usr/bin/env python3
"""Generate zig/sources.zig from the CMake/ninja ground truth.

Spike tool: parses the output of `ninja -t commands realm_dart` (from a CMake
configure of packages/realm_dart with REALM_ENABLE_SYNC=OFF and
REALM_ENABLE_ENCRYPTION=OFF) and emits a Zig source manifest consumed by
build.zig.

Usage:
    cmake -G Ninja -B <builddir> -DCMAKE_BUILD_TYPE=Release \
        -DREALM_ENABLE_SYNC=OFF -DREALM_ENABLE_ENCRYPTION=OFF \
        -DREALM_APP_SERVICES=OFF
    ninja -C <builddir> -t commands realm_dart > commands.txt
    python3 zig/gen_sources.py commands.txt <builddir>
"""

import shlex
import sys
from collections import defaultdict
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    commands_file, build_dir = sys.argv[1], Path(sys.argv[2]).resolve()
    generated_include = build_dir / "src" / "realm-core" / "src"

    groups: dict[tuple, list[str]] = defaultdict(list)
    all_includes: list[str] = []

    for line in Path(commands_file).read_text().splitlines():
        tokens = shlex.split(line)
        if "-c" not in tokens:
            continue  # archive/link/phony commands
        src = Path(tokens[tokens.index("-c") + 1]).resolve()
        lang = "cpp" if tokens[0].endswith("c++") else "c"

        defines, std = [], None
        for i, tok in enumerate(tokens):
            if tok.startswith("-D"):
                defines.append(tok)
            elif tok.startswith("-std="):
                std = tok
            elif tok == "-I" or tok == "-isystem":
                _add_include(all_includes, Path(tokens[i + 1]), generated_include)
            elif tok.startswith("-I"):
                _add_include(all_includes, Path(tok[2:]), generated_include)

        key = (lang, std, tuple(sorted(defines)))
        groups[key].append(_rel(src))

    _emit(groups, all_includes)


def _rel(path: Path) -> str:
    return path.relative_to(PACKAGE_ROOT).as_posix()


def _add_include(includes: list[str], path: Path, generated: Path) -> None:
    path = path.resolve()
    if path == generated:
        return  # build.zig generates config.h/version_numbers.hpp itself
    entry = _rel(path)
    if entry not in includes:
        includes.append(entry)


def _emit(groups, includes) -> None:
    out = Path(__file__).parent / "sources.zig"
    with out.open("w") as f:
        f.write("// Generated by zig/gen_sources.py — do not edit by hand.\n")
        f.write("// Ground truth: CMake configure of realm_dart with sync/encryption OFF.\n\n")
        f.write("pub const Group = struct {\n")
        f.write("    language: enum { c, cpp },\n")
        f.write("    flags: []const []const u8,\n")
        f.write("    files: []const []const u8,\n")
        f.write("};\n\n")
        f.write("pub const include_dirs = [_][]const u8{\n")
        for inc in includes:
            f.write(f'    "{inc}",\n')
        f.write("};\n\n")
        f.write("pub const groups = [_]Group{\n")
        for (lang, std, defines), files in sorted(groups.items()):
            flags = [std] if std else []
            flags += list(defines)
            f.write("    .{\n")
            f.write(f"        .language = .{lang},\n")
            f.write("        .flags = &.{ " + ", ".join(f'"{x}"' for x in flags) + " },\n")
            f.write("        .files = &.{\n")
            for src in sorted(files):
                f.write(f'            "{src}",\n')
            f.write("        },\n    },\n")
        f.write("};\n")
    n = sum(len(v) for v in groups.values())
    print(f"wrote {out} ({n} files, {len(groups)} groups, {len(includes)} include dirs)")


if __name__ == "__main__":
    main()
